lbryio/lbry-web-ui

- js/page/home.js
@alexliebowitz A couple minor UI changes that hopefully you'll like as well
> bold titles, better image sizes, minor rework of homepage

- js/component/common.js
- js/page/home.js
Adds the Community Content section to the front page, with a "what's this?" tooltip that explains what it's all about.
> Community content (WIP)

- js/page/publish.js
Also pre-fills bid from the existing claim (fee and metadata fields coming soon)
> Change wording and behavior on Publish page when user already controls name

- .travis.yml
- LICENSE.md
- README.md
- package.json
- watch.sh
Adds `package.json` with actual requirements
> Easier install

- js/lbry.js
- js/page/discover.js
- js/page/settings.js
- scss/_canvas.scss
- scss/_global.scss
- scss/_gui.scss
Also adds a mouse-over overlay explaining you can choose to show NSFW stuff on the Settings page (not implemented yet)
> Blur NSFW stuff on home page (WIP)

- js/app.js
- js/component/drawer.js
- js/lbry.js
- js/page/my_files.js
- js/page/publish.js
Depends on [this](https://github.com/lbryio/lbry-web-ui/pull/57) lbry-web-ui PR and [this](https://github.com/lbryio/lbry/pull/165) lbrynet PR.
> Separate tabs for Downloaded and Published files in My Files

- js/component/common.js
- js/lbry.js
- js/page/wallet.js
- Remembers address from previous views using local storage
- Also improved layout and added help text
> Show address on Wallet page

- js/component/form.js
- js/page/publish.js
Includes the six standard CC licenses plus Copyrighted, Public Domain, and Other, with various options that pop up based on which one you choose.
> Convert license field to drop-down box

- js/page/discover.js
- scss/_canvas.scss
Alters styles to make room for more description text, uses &lt;TruncatedText&gt; to limit titles to two lines and descriptions to 3 lines
> Fix Featured and Community Content descriptions getting cut off

- js/lbry.js
- js/page/publish.js
Now possible because of the new [get_my_claim()](https://github.com/lbryio/lbry/pull/165) JSON-RPC method.
> Add better feedback for non-winning claims on Publish page

- js/lbry.js
- js/lighthouse.js
- js/page/discover.js
- js/page/my_files.js
- js/page/show.js
Resolves this issue: https://app.asana.com/0/114030215896582/207564800401486
> Retry search on a different server if connection to Lighthouse fails (WIP)

- js/page/wallet.js
Fixes this issue: https://app.asana.com/0/198587529699250/203787409913745
> On Wallet page, show placeholder text for dates on pending transactions

- js/page/publish.js
> Publish: prevent submit and notify user if file is not fully processed

- js/lbry.js
- js/page/publish.js
If the user tries to type an invalid character, this will reject it and pop up a form hint explaining what characters are allowed in a LBRY name.
> Reject invalid name characters on Publish page

- js/page/help.js
Depends on this lbrynet PR: https://github.com/lbryio/lbry/pull/287
> Help: Show LBRY ID in "About" section

- js/lbry.js
- js/page/help.js
Needed to sync up with changes in https://github.com/lbryio/lbry/pull/287. Also bumps the required version to 0.7.7.
> Update API method used to get LBRY ID

- package.json
- webpack.config.js
Fixes some IE bugs, plus gives us a few more ES2015 features.
> Add Babel Polyfill

- js/app.js
- js/lbry.js
- js/lighthouse.js
- js/main.js
- js/page/developer.js
- scss/_gui.scss
- scss/all.scss
- scss/page/_developer.scss
Similar to the main Settings page, with two options for developers only:
- Debug mode (exposes the lbry and lighthouse modules in global namespace; makes it easier to work in the JS console)
- Custom Lighthouse servers
> Developer Settings page (WIP)

- js/app.js
- js/page/discover.js
The "no results found" message was showing instead due to some tricky state management stuff. Also, the BusyMessage component wasn't being imported.
> Restore Dewey Decimals message in searches

- js/lbry.js
- js/page/report.js
- Fixes imports
- Now uses new report_bug daemon method
> Update Report Bug page

- js/app.js
- js/lbry.js
The API method for this (get_start_notice()) is now deprecated
> Remove startup notice code

- js/app.js
- js/component/link.js
- js/page/claim_code.js
- js/page/my_files.js
- js/page/publish.js
- js/page/referral.js
- js/page/report.js
- js/page/wallet.js
Fixes this issue: https://app.asana.com/0/114030215896582/237763457319359
> Add ARIA labels for all modals

- js/component/file-actions.js
- js/component/link.js
- js/lbry.js
- scss/_global.scss
- scss/_gui.scss
- scss/component/_file-actions.scss
- scss/component/_menu.scss
Once these are approved, unavailable content is ready for production.
> Unavailable content bugfixes

- js/component/load_screen.js
There were some !s in there that were only for debugging
> Remove debug logic in load_screen.js

- .travis.yml
- CHANGELOG.md
- Dangerfile
Start recording changes in a changelog.  See http://keepachangelog.com/ for details.
> Add changelog and check

- CHANGELOG.md
- js/page/watch.js
- scss/all.scss
- scss/page/_watch.scss
Code is basically done, but not mergeable yet because it includes code to imitate Job's new HTML5 player on the Electron branch.
> Add Back button to Watch page (WIP)

- dist/requirements.txt
- js/lbry.js
Formerly polled the full list of files; now looks up the specific file by name.
Made possible by this lbrynet PR: https://github.com/lbryio/lbry/pull/485
> Update how Publish page polls for file appearing in file manager

- js/component/file-actions.js
- js/lbry.js
More info than peer_count, and now has built-in timeout
> Use get_availability to determine stream availability

- js/app.js
- js/component/file-actions.js
- js/component/file-tile.js
- Fix wrong prop types for metadata (was causing console warnings)
- Add link styles back to Try Anyway link (were lost in PR)
- Remove incorrectly formatted comment in app.js
> Misc. bug fixes

- CHANGELOG.md
- js/app.js
- js/component/modal.js
- scss/_gui.scss
- Restore centering of modal headers
- Refactor Modal component
- Add new ExpandableModal component and convert error modal to use it
> Improvements to modals

- CHANGELOG.md
- js/component/drawer.js
- js/lbry.js
- js/main.js
- js/page/developer.js
Also added the ability to access Developer Settings by holding Ctrl-Shift or Cmd-Shift and clicking the LBRY logo. https://youtu.be/pXPXMxsXT28
Depends on this lbry-app PR: https://github.com/lbryio/lbry-app/pull/9
> Add option in Developer Settings to enable/disable developer menu

- CHANGELOG.md
- js/lbry.js
- Fix variable name of default client setting
- Correct key combo details in change log entry
> Quick tweaks to developer menu
