- js/app.js
Needs to be https://www.lbry.io/get. For some reason if it's non https, it redirects to https://www.lbry.io/news/get.
> Change update location

- js/page/my_files.js
Is there a reason they can show up more than once? Should this be filtered by daemon instead?
> only print an item in my_files once

- js/page/show.js
The Watch and Download buttons on the Show page were nonfunctional. This fixes that bug.
> fix watch/download links on ?show= page

- js/lbry.js
- js/page/discover.js
- js/page/my_files.js
- js/page/show.js
Also makes it possible to detect media type via MIME type, not just filename (filename isn't always available and it's less reliable)
> Hide Watch button for non-video content everywhere, not just My Files page

- js/page/wallet.js
Previously, the transaction log only listed positive (incoming) transactions. Now it also shows negative (outgoing) transactions. Transactions with zero net effect on balance are still hidden.
> show negative transactions

- js/lbry.js
- js/page/my_files.js
- js/page/publish.js
- Make the Publish page send the user to the My Files screen as soon as the publication process starts, instead of when the file is already published and waiting for confirmation
- On My Files, add a message when the file is published but still uploading to Lighthouse (the formatting of this will change, maybe even an icon with tooltip instead of a message)
To do: Add a separate message for when the file is processing but not yet waiting for confirmation, and possibly for other stages. It may even be possible to do a progress bar.
> Make Publish process snappier and more informative (WIP)

- .travis.yml
Reverts lbryio/lbry-web-ui#66
Because of https://github.com/travis-ci/travis-ci/issues/1670, using tags doesn't work with the current release process for the web-ui.  Need to rework!
> Revert "only deploy on a tag"

- js/component/common.js
- js/page/discover.js
- js/page/my_files.js
- js/page/show.js
Adds a new Thumbnail component and converts all thumbnail images to use it.
Features:
- If something empty or false is provided for the URL, displays the default thumbnail. Before, you had to do `<img src={thumbnail_url || '/img/default-thumb.svg'}>`
- If image fails to load, falls back on default thumbnail
- Also will fall back to default thumbnail if image takes more than 10 seconds to load
Resolves this issue: https://app.asana.com/0/198587529699250/207421714255318
> Thumbnail component

- js/component/drawer.js
Before, it was failing to highlight the drawer item when a different sub-tab was chosen (e.g. if you chose My Files and then go to Published, My Files would un-highlight in the drawer).
This solution feels kinda hacky--it might be better if we could somehow store the paths for the sub-pages in the App component, or even the individual page components. But AFAIK we're still planning to re-do the whole routing system at some point so I decided not to overthink it.
Resolves this issue: https://app.asana.com/0/search/211398218008538/207421714255316
> Highlight drawer item for sub-pages

- js/page/publish.js
Fix issues with display of bids on Publish page
- Display exact amounts for bids (was using lbry.formatCredits before, so bids lower than than 0.1 credits were displaying as 0.0)
- Correctly pluralize "credit" vs. "credits" for bid amounts
- Display top bid correctly (before, it would sometimes show the user's bid instead) 
- Wording tweak: it said you must bid "at least ___ credits" to outbid an existing claim, now says "more than ___ credits"
Resolves this issue: https://app.asana.com/0/198587529699250/204870560230668
> Fix issues with display of bids on Publish page

- js/lbry.js
Name-formatter now replaces spaces with dashes, for more readable names. This is similar to Wordpress' permalink processing.
> formatName - replace spaces with dashes

- js/page/publish.js
Previously, if the user typed a name that they have a claim on and then continued typing, some of the interface would not be updated to show that they don't have a claim.
> Fix issue with live updating logic on Publish page

- js/component/link.js
- js/component/modal.js
Download links:
- Switch to "Downloading" immediately on click (don't wait for balance check to finish)
- Don't bother to check this.state.downloading on click
- Properly notify the user when a download times out
Watch links:
- Disable on click so the user can tell something is happening during the balance check
All modals:
- Wrap contents of modals in div to prevent flexbox layout (was causing things to be laid out in their own line just because they were wrapped in a `<strong>` element, etc).
> Improvements to Watch and Download links

- js/component/link.js
- scss/_gui.scss
This displays the file path on its own line and does character-level wrapping on the path only.
Ideally, we would just apply character wrapping to all words that are too long to fit on one line, and use normal word wrapping for everything else. There are CSS props for this like `overflow-wrap` and `word-break`, but I haven't been able to find a way to do it cross-browser without setting a width on the outer container, which we don't want here (modals stretch based on their content). So this is the best compromise I could come up with. 
Fixes this issue: https://app.asana.com/0/search/223675889679358/215539621304348
> Change wrapping of file path in "Download Succeeded" Modal

- js/app.js
Avoid text like "Click 'Upgrade' to XXX" that tells the user how to do something that the UI already invites them to do.
> Tweak upgrade message

- js/lbry.js
- js/page/my_files.js
Reduces the check interval to once every 5 minutes to avoid slamming peers with requests. I'll improve this later: it would be better to not check at all for a couple of minutes after a publish starts, then switch to a higher rate (say once a minute). Also, right now it monitors availability for all files. It should only be looking at files currently being published.
> My Files page: during publication, check for availability directly from peers instead of with Lighthouse

- js/lbry.js
- js/lighthouse.js
- js/page/discover.js
- js/page/show.js
The new Lighthouse doesn't report costs; instead it reports a file size that can be used to calculate the cost. This PR updates the Discover and Show pages to look up the file size with Lighthouse and ask lbrynet to compute the cost. If Lighthouse is down or doesn't have the file size, it falls back to just showing the key fee.
Also includes some light refactoring and UX improvements on both pages, e.g. both pages will now load if Lighthouse is down.
> Update Discover and Show pages to use new Lighthouse cost reporting

- js/lbry.js
- js/page/my_files.js
This PR heavily refactors the My Files page. The main change is that the "Published" and "Downloaded" pages now use separate logic to generate their lists of files.
- Published page now looks up the user's claims instead of files. This allows published streams to be listed even if the files don't exist on the user's machine; also, because it looks up file info by txid, you will no longer see a newer claim listed if you made a claim and it was overtaken.
- Downloaded page works pretty much the same as before
- Checking for file ownership is now done by making one call to lbry.getMyClaims() and saving a list of txids of streams published by the user. Before, it was making a call to lbry.getFilesInfo() and checking ownership on each one, which was way slower.
- Also added a message to the …
> Refactor My Files page (WIP)

- dist/index.html
- js/page/watch.js
Needed because MediaElement doesn't fully support ES6 modules yet
> Import MediaElement with <script> tag

- js/page/my_files.js
- Simplify sorting logic (performs sort on every render instead of trying to always keep `this.state.filesInfo` sorted)
- When building up the list of claims for the Published tab, preserve original order returned by `lbry.getMyClaims()` so the list doesn't get scrambled up if the API calls inside the loop return out of order.
> My Files: fix "Date" sorting in Published tab

- js/component/common.js
Was sometimes trying to check if the image loaded after the component was already unmounted.
Fixes this issue: https://app.asana.com/0/198587529699250/237373045470608
> Fix uncaught type error in Thumbnail

- dist/index.html
- dist/js/mediaelement/mediaelement-and-player.js
- js/page/watch.js
Needed because Safari now reports that Flash isn't installed, even when it is: https://webkit.org/blog/6589/next-steps-for-legacy-plug-ins/
> Bypass check for Flash being installed in MediaElement.js

- webpack.config.js
For now we only need the Stage 2 Babel plugin, not Stage 3.
> Update Webpack preset list

- js/component/file-tile.js
- js/lbry.js
On search results pages, stream_cost_estimate is called on every result. If there's some problem in the daemon that affects all calls to stream_cost_estimate, this can lead to 25 error boxes. Better to just suppress the error and not display a price.
Also switched to the new name for the daemon method (get_cost_est -> stream_cost_estimate).
Addresses this issue: https://app.asana.com/0/198587529699250/251016570437119
> Don't show error message if price for a file can't be retrieved

- js/component/file-actions.js
- js/component/file-tile.js
- js/component/link.js
- js/component/menu.js
Due to recent changes, they were appearing as text buttons
> Fix styling of normal text links

- js/lbry.js
lbry.getFileInfoWhenListed() now only times out if a timeout callback is provided.
> Don't time out on Publish page

- js/component/common.js
- package.json
- scss/_gui.scss
Once we're fully on Electron, we can take out clamp.js altogether, because Chromium has native line clamping.
> Fix line clamping on Firefox

- js/page/watch.js
Before, it wouldn't recognize "stopped" status as a playable state.
> Fix status check on Watch page

- js/component/file-actions.js
- js/component/link.js
- js/component/menu.js
- scss/_gui.scss
- scss/component/_menu.scss
- Buttons on dialogs were not getting width and height
- Tooltip buttons were getting standard button spacing when they should be closer to their corresponding menu button
- Several buttons and other elements had containers just to get spacing in button sets; rename button-container class to button-set-item and apply directly to elements where possible.
> Fix several problems with margin and padding on buttons

- CHANGELOG.md
- js/page/watch.js
- scss/all.scss
- scss/page/_watch.scss
Add the Back button back to the Watch page. It was previously lost in a tragic merging incident. Also added a changelog entry and fixed a bug causing the button to flicker when you move the mouse over it.
> Re-integrate Back button on Watch page

- CHANGELOG.md
- js/component/load_screen.js
Before, it was only showing if a load attempt timed out, and would show even if there was no previous page to go back to.
> On load screen, always show Cancel link if a previous page is available
